language: python
python:
  - “3.9“

sudo: false

env:
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6

install:
  - pip install -q Django==3.1.6
  - python setup.py -q install
  - pip install -r requirements.txt

branches:
  only:
    - master

script:
  # - python manage.py runserver
  - python manage.py runserver 0.0.0.0:8000

