language: python
python:
  - “3.9“

sudo: false

install:
  # - pip install -q Django==3.1.6
  - pip install -r requirements.txt

branches:
  only:
    - master

script:
  - python manage.py test
  # - python manage.py runserver 0.0.0.0:8000

