language: python
python:
  - “3.9“

install:
  - pip install -r requirements.txt

sudo: false

branches:
  only:
    - master

script:
  # - python manage.py runserver
  - python manage.py runserver 0.0.0.0:8000

